# Services auto-reroute requests when a deployment gets updated and new pods are brought up (will have diff PI addr potentially)
# This provides clients a persistent address to access deployment pods through
apiVersion: v1
kind: Service
metadata:
  name: client-node-port
spec:
  # really only good for dev purposes since it exposes the pod to the outside world at some port which you don't want in a prod env
  type: NodePort
  ports:
      # port used by other pods in node to access the client-pod
    - port: 3050
      # port that k8s will route incoming requests for the client-pod to, e.g. 3050 -> 3000, 31515 -> 3000
      targetPort: 3000
      # port used to access client-pod from outside the current node
      nodePort: 31515
  selector:
    component: web