apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  # deployment itself doesn't create the pod - the k8s master does, it uses the selector to find the created pod
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: client
          image: sterelus/multi-client
          ports:
            - containerPort: 3000